In [64]:
#@title
from IPython.display import HTML, display

HTML("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap');

:root {
    --bg: #07090d;
    --card: #10141b;
    --card2: #151a22;
    --white: #f5f7fa;
    --gray: #9da6b5;
    --gold: #D4AF37;
    --blue: #0085C7;
    --black: #111111;
    --red: #DF0024;
    --yellow: #F4C300;
    --green: #009F3D;
}

* {
    box-sizing: border-box;
}

.olympic-container {
    font-family: 'Montserrat', sans-serif;
    background:
        radial-gradient(circle at 50% 0%, rgba(0,133,199,.13), transparent 35%),
        radial-gradient(circle at 85% 80%, rgba(212,175,55,.08), transparent 30%),
        var(--bg);
    color: var(--white);
    padding: 45px 35px 55px;
    border-radius: 24px;
    max-width: 1200px;
    margin: 20px auto;
    overflow: hidden;
    border: 1px solid #252b35;
    box-shadow: 0 25px 70px rgba(0,0,0,.45);
}

/* CABECERA */

.top-info {
    text-align: center;
    margin-bottom: 25px;
}

.subject {
    color: var(--gold);
    font-size: 15px;
    font-weight: 700;
    letter-spacing: 2px;
    text-transform: uppercase;
}

.year {
    color: #8993a3;
    font-size: 13px;
    margin-top: 6px;
}

/* TITULO */

.badge {
    display: inline-block;
    padding: 7px 15px;
    border: 1px solid rgba(212,175,55,.5);
    border-radius: 30px;
    color: var(--gold);
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 1.5px;
    text-transform: uppercase;
    margin-bottom: 18px;
}

.main-title {
    text-align: center;
    font-size: clamp(30px, 5vw, 52px);
    line-height: 1.08;
    font-weight: 800;
    margin: 0;
    background: linear-gradient(90deg, #ffffff, #D4AF37, #ffffff);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.subtitle {
    text-align: center;
    color: var(--gray);
    font-size: 15px;
    margin: 15px auto 28px;
    max-width: 750px;
}

/* ALUMNOS */

.students {
    display: flex;
    justify-content: center;
    gap: 15px;
    flex-wrap: wrap;
    margin: 0 auto 35px;
}

.student {
    background: rgba(255,255,255,.035);
    border: 1px solid #292f39;
    padding: 12px 20px;
    border-radius: 12px;
    text-align: center;
    min-width: 250px;
    transition: .3s ease;
}

.student:hover {
    transform: translateY(-3px);
    border-color: var(--gold);
    box-shadow: 0 8px 25px rgba(212,175,55,.12);
}

.student-name {
    font-weight: 700;
    font-size: 13px;
    color: white;
}

.student-dni {
    font-size: 11px;
    color: #8993a3;
    margin-top: 4px;
}

/* ANILLOS */

.rings-wrapper {
    position: relative;
    width: 420px;
    max-width: 100%;
    height: 145px;
    margin: 15px auto 38px;
}

.ring {
    position: absolute;
    width: 82px;
    height: 82px;
    border-radius: 50%;
    background: transparent;
    border: 7px solid;
    cursor: pointer;
    transition:
        transform .35s ease,
        box-shadow .35s ease,
        filter .35s ease;
    z-index: 2;
}

.ring:hover {
    transform: scale(1.12);
    filter: brightness(1.25);
}

.ring.active {
    transform: scale(1.16);
    filter: brightness(1.35);
    z-index: 5;
}

.ring-blue {
    border-color: var(--blue);
    left: 42px;
    top: 15px;
}

.ring-black {
    border-color: #eeeeee;
    left: 125px;
    top: 15px;
}

.ring-red {
    border-color: var(--red);
    left: 208px;
    top: 15px;
}

.ring-yellow {
    border-color: var(--yellow);
    left: 83px;
    top: 57px;
}

.ring-green {
    border-color: var(--green);
    left: 166px;
    top: 57px;
}

/* ESTADISTICAS */

.stats {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin-bottom: 35px;
}

.stat {
    background: linear-gradient(145deg, #11161e, #0c1016);
    border: 1px solid #252c36;
    border-radius: 14px;
    padding: 18px 10px;
    text-align: center;
    transition: .3s ease;
}

.stat:hover {
    transform: translateY(-4px);
    border-color: rgba(212,175,55,.55);
}

.stat-number {
    color: var(--gold);
    font-size: 25px;
    font-weight: 800;
}

.stat-label {
    color: var(--gray);
    font-size: 10px;
    margin-top: 5px;
    text-transform: uppercase;
    letter-spacing: .7px;
}

/* CONTENIDO */

.content-panel {
    background: linear-gradient(145deg, #11161e, #0d1117);
    border: 1px solid #252c36;
    border-radius: 18px;
    padding: 30px;
    min-height: 235px;
    animation: fadeIn .35s ease;
    scroll-margin-top: 40px;
}

@keyframes fadeIn {
    from {
        opacity: 0;
        transform: translateY(8px);
    }

    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.panel-title {
    color: var(--gold);
    font-size: 22px;
    font-weight: 800;
    margin-bottom: 15px;
}

.panel-text {
    color: #c4cad4;
    font-size: 14px;
    line-height: 1.8;
}

.panel-text strong {
    color: white;
}

/* FOOTER */

.footer {
    text-align: center;
    color: #596270;
    font-size: 10px;
    margin-top: 28px;
    letter-spacing: 1px;
}

/* RESPONSIVE */

@media (max-width: 700px) {

    .olympic-container {
        padding: 30px 18px;
    }

    .stats {
        grid-template-columns: repeat(2, 1fr);
    }

    .rings-wrapper {
        transform: scale(.82);
        margin-top: -5px;
        margin-bottom: 20px;
    }

    .content-panel {
        padding: 22px;
    }

    .students {
        flex-direction: column;
        align-items: center;
    }

    .student {
        width: 100%;
    }
}
</style>


<div class="olympic-container">

    <!-- CABECERA -->

    <div class="top-info">

        <div class="subject">
            Práctica Profesionalizante I
        </div>

        <div class="year">
            2026
        </div>

    </div>


    <!-- TITULO -->

    <div style="text-align:center;">

        <div class="badge">
            Análisis de Datos · Juegos Olímpicos
        </div>

    </div>


    <h1 class="main-title">
        Análisis Exploratorio de Datos<br>
        de los Juegos Olímpicos
    </h1>


    <div class="subtitle">
        Participación · Rendimiento · Medallas · Localía · 1992 — 2026
    </div>


    <!-- ALUMNOS -->

    <div class="students">

        <div class="student">

            <div class="student-name">
                Portal, Gustavo Gabriel
            </div>

            <div class="student-dni">
                
            </div>

        </div>


        <div class="student">

            <div class="student-name">
                Carrillo, Rubén Matías
            </div>

            <div class="student-dni">
                
            </div>

        </div>

    </div>


    <!-- ANILLOS INTERACTIVOS -->

    <div class="rings-wrapper">

        <div
            class="ring ring-blue"
            onclick="showSection('objetivo', this)"
            title="Objetivo">
        </div>


        <div
            class="ring ring-black"
            onclick="showSection('hipotesis', this)"
            title="Hipótesis">
        </div>


        <div
            class="ring ring-red"
            onclick="showSection('preparacion', this)"
            title="Preparación">
        </div>


        <div
            class="ring ring-yellow"
            onclick="showSection('exploracion', this)"
            title="Exploración">
        </div>


        <div
            class="ring ring-green"
            onclick="showSection('conclusiones', this)"
            title="Conclusiones">
        </div>

    </div>


    <!-- ESTADISTICAS -->

    <div class="stats">

        <div class="stat">

            <div class="stat-number">
                166K+
            </div>

            <div class="stat-label">
                Registros analizados
            </div>

        </div>


        <div class="stat">

            <div class="stat-number">
                19
            </div>

            <div class="stat-label">
                Ediciones olímpicas
            </div>

        </div>


        <div class="stat">

            <div class="stat-number">
                9 / 10
            </div>

            <div class="stat-label">
                Verano / Invierno
            </div>

        </div>


        <div class="stat">

            <div class="stat-number">
                3
            </div>

            <div class="stat-label">
                Hipótesis
            </div>

        </div>

    </div>


    <!-- PANEL INTERACTIVO -->

    <div id="content-panel" class="content-panel">

        <div class="panel-title">
            🏅 Seleccioná un anillo
        </div>

        <div class="panel-text">

            Los anillos olímpicos funcionan como botones
            interactivos.

            Cada uno representa una etapa diferente del análisis
            realizado sobre los Juegos Olímpicos entre 1992 y 2026.

            <br><br>

            <strong>
                Hacé clic sobre cualquiera de los anillos para comenzar.
            </strong>

        </div>

    </div>


    <!-- FOOTER -->

    <div class="footer">

        ANÁLISIS EXPLORATORIO DE DATOS ·
        PRÁCTICA PROFESIONALIZANTE I · 2026

    </div>

</div>


<script>

function showSection(section, element) {


    /* ---------------------------------
       QUITAR ESTADO ACTIVO
    --------------------------------- */

    document.querySelectorAll('.ring').forEach(function(ring) {

        ring.classList.remove('active');

    });


    /* ---------------------------------
       ACTIVAR ANILLO SELECCIONADO
    --------------------------------- */

    element.classList.add('active');


    /* ---------------------------------
       CONTENIDO DE CADA SECCIÓN
    --------------------------------- */

    const content = {


        objetivo: {

            title: "🎯 Objetivo del análisis",

            text: `

                El objetivo de este trabajo es realizar un
                <strong>Análisis Exploratorio de Datos (EDA)</strong>
                sobre la participación y el rendimiento de los países
                en los Juegos Olímpicos.

                <br><br>

                Se busca identificar relaciones y patrones entre
                variables como la cantidad de atletas participantes,
                las medallas obtenidas, el tamaño de las delegaciones,
                la temporada olímpica y la condición de país anfitrión.

            `

        },


        hipotesis: {

            title: "💡 Hipótesis planteadas",

            text: `

                Durante el análisis se plantearon
                <strong>tres hipótesis principales</strong>:

                <br><br>

                <strong>H1.</strong>
                Existe una relación positiva entre la cantidad de
                atletas participantes y la cantidad de medallas
                obtenidas por país, con posibles diferencias entre
                Juegos de Verano e Invierno.

                <br><br>

                <strong>H2.</strong>
                Los países que obtienen una mayor cantidad total de
                medallas no necesariamente presentan una mayor
                eficiencia en relación con la cantidad de atletas
                participantes.

                <br><br>

                <strong>H3.</strong>
                Los países anfitriones obtienen, en promedio, una
                mayor cantidad de medallas cuando compiten como locales.

            `

        },


        preparacion: {

            title: "🧹 Preparación de los datos",

            text: `

                El conjunto de datos original contiene más de
                <strong>315.000 registros</strong> y 15 variables
                relacionadas con atletas y participaciones olímpicas.

                <br><br>

                Para este trabajo se seleccionaron las ediciones
                comprendidas entre <strong>1992 y 2026</strong>,
                obteniendo aproximadamente
                <strong>166.000 registros</strong>.

                <br><br>

                También se realizaron procesos de limpieza,
                transformación y agrupación de los datos para poder
                analizar correctamente la cantidad de atletas y
                las medallas obtenidas por cada país.

            `

        },


        exploracion: {

            title: "📊 Exploración y visualización",

            text: `

                El análisis se realizó mediante diferentes técnicas
                de estadística descriptiva y visualización de datos.

                <br><br>

                Se utilizaron principalmente gráficos interactivos
                desarrollados con <strong>Plotly</strong>, permitiendo
                explorar relaciones entre variables y observar
                diferencias entre países, temporadas y condiciones
                de localía.

                <br><br>

                Entre las herramientas utilizadas se encuentran
                gráficos de dispersión, barras, correlaciones,
                agrupaciones y comparaciones entre delegaciones.

            `

        },


        conclusiones: {

            title: "🏅 Conclusiones",

            text: `

                El análisis permitió identificar diferentes relaciones
                entre la participación y el rendimiento olímpico.

                <br><br>

                La primera hipótesis encontró respaldo en cuanto a la
                existencia de una relación positiva fuerte entre
                cantidad de atletas y medallas, con una correlación
                aproximada de <strong>0,88</strong>.

                Sin embargo, no se observaron diferencias marcadas
                entre Juegos de Verano e Invierno.

                <br><br>

                En la segunda hipótesis se observó que la cantidad
                total de medallas y la eficiencia representan medidas
                diferentes del rendimiento de una delegación.

                <br><br>

                Finalmente, los países anfitriones obtuvieron en promedio
                <strong>36,89 medallas</strong>, frente a
                <strong>20,65</strong> cuando no fueron anfitriones,
                dentro del conjunto analizado.

            `

        }

    };


    /* ---------------------------------
       OBTENER SECCIÓN SELECCIONADA
    --------------------------------- */

    const selected = content[section];


    /* ---------------------------------
       BUSCAR PANEL
    --------------------------------- */

    const panel = document.getElementById('content-panel');


    /* ---------------------------------
       REINICIAR ANIMACIÓN
    --------------------------------- */

    panel.style.animation = 'none';

    panel.offsetHeight;

    panel.style.animation = 'fadeIn .35s ease';


    /* ---------------------------------
       ACTUALIZAR CONTENIDO
    --------------------------------- */

    panel.innerHTML = `

        <div class="panel-title">
            ${selected.title}
        </div>

        <div class="panel-text">
            ${selected.text}
        </div>

    `;


    /* ---------------------------------
       DESPLAZAMIENTO SUAVE
    --------------------------------- */

    setTimeout(function() {

        panel.scrollIntoView({

            behavior: 'smooth',

            block: 'center'

        });

    }, 100);

}

</script>
""")

# **Práctica Profesionalizante 1: Proyecto Final** 🥇 🥈 🥉

👨‍🏫 Profesor:

- Paredes, Julio

# Abstract

## Análisis del rendimiento de los países en los Juegos Olímpicos 🏅

En este proyecto realizaremos un Análisis Exploratorio de Datos (EDA) sobre la participación y el rendimiento de los países participantes de los **Juegos Olímpicos**, considerando tanto los Juegos de Verano como los de Invierno.

El objetivo es explorar características relacionadas con la participación y el desempeño de los países, buscando identificar patrones entre la cantidad de atletas participantes, las medallas obtenidas y otras condiciones que podrían estar asociadas con el rendimiento, como la temporada en que se desarrollan los Juegos y el hecho de competir como país anfitrión.

El conjunto de datos utilizado se encuentra en un archivo en formato **.CSV** y contiene información histórica sobre la participación de atletas en los Juegos Olímpicos. El dataset completo posee más de **315.000 registros y 15 variables**.

Para este proyecto decidimos trabajar con los registros correspondientes al período comprendido entre **1992-2026**. Este recorte permite analizar un período relativamente reciente y con una amplia participación internacional, incluyendo tanto los Juegos Olímpicos de Verano como los de Invierno. De esta selección se obtiene un conjunto de aproximadamente **166.000 registros**, correspondientes a **19 ediciones olímpicas: 9 de Verano y 10 de Invierno**.

Entre las principales variables disponibles se encuentran:

* identificación y nombre de los atletas;
* sexo;
* edad;
* altura y peso;
* equipo y país representado;
* edición y año de los Juegos Olímpicos;
* temporada: Verano o Invierno;
* ciudad sede;
* deporte;
* evento o prueba disputada;
* medalla obtenida.

A partir de estas variables se buscará analizar la relación entre el **tamaño de las delegaciones y cantidad de medallas obtenidas**, considerando además posibles diferencias entre los Juegos Olímpicos de Verano y de Invierno.

También se analizará la eficiencia en la obtención de medallas en relación con la cantidad de atletas participantes, con el objetivo de comparar el desempeño de los países independientemente del tamaño de sus delegaciones.

Finalmente, se estudiará el posible **efecto de la localía**, comparando la cantidad de medallas obtenidas por los países cuando fueron anfitriones de los Juegos con las obtenidas en otras ediciones que no fueron sede.

Para comprobar las hipótesis, primero se realizará el **preprocesamiento y limpieza de los datos**. Posteriormente se utilizarán resúmenes estadísticos y técnicas de visualización mediante **gráficos interactivos**, como gráficos de barras y diagramas de dispersión, que permitan identificar patrones y presentar resultados de manera comprensible.

# Preguntas e Hipótesis de Interés ❓

## 1. Cantidad de atletas y cantidad de medallas

**Pregunta**

¿Existe una relación entre la cantidad de atletas que presenta un país y la cantidad de medallas que obtiene? ¿Esta relación es diferente entre los Juegos Olímpicos de Verano y los de Invierno?

**Hipótesis H1**

Existe una relación positiva entre la cantidad de atletas participantes y la cantidad de medallas obtenidas por país, pero esta relación presenta diferencias entre los Juegos Olímpicos de Verano y los de Invierno.

---

## 2. Eficiencia de medallas por atleta

**Pregunta**

¿Qué países presentan una mayor cantidad de medallas obtenidas en relación con la cantidad de atletas participantes?

**Hipótesis H2**

Los países que poseen una mayor cantidad de medallas no necesariamente son aquellos que presentan las delegaciones con mayor cantidad de atletas participantes.

Para explorar esta relación se considerará una medida de eficiencia:

**Eficiencia = cantidad de medallas / cantidad de atletas**

Esto permitirá comparar países con delegaciones de diferentes tamaños.

---

## 3. Rendimiento de los países anfitriones

**Pregunta**

¿Los países anfitriones obtienen una mayor cantidad de medallas cuando compiten como locales que cuando participan en otras ediciones?

**Hipótesis H3**

Los países anfitriones obtienen una mayor cantidad de medallas en la edición que organizan que en aquellas ediciones en las que participan sin ser sede.

# Preprocesamiento 🧹

Se procederá en esta sección a:

* Importación de las librerías necesarias.
* Carga del dataset.
* Inspección inicial de su estructura.
* Filtrado de los registros correspondientes al período **1992-2026**.
* Selección de las variables necesarias para el análisis.
* Revisión de los tipos de datos.
* Verificación de valores nulos.
* Análisis de los valores faltantes y tratamiento cuando sea necesario.
* Chequeo de registros duplicados.
* Identificación de atletas únicos.
* Preparación del conteo de medallas para evitar duplicaciones producidas por deportes o eventos por equipos.
* Creación de variables calculadas necesarias para responder las preguntas planteadas.
* Agrupación de los datos por país, edición y temporada cuando corresponda.
* Preparación de los datos para la creación de gráficos interactivos y el posterior análisis exploratorio.

## Montar google drive

## Importar Librerias

In [65]:
# Importar librerías

import numpy as np
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [66]:
# Configuración de visualización

np.set_printoptions(linewidth=500)

pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)
pd.set_option("display.width", None)

## Importar el Dataset

In [67]:
url = "https://raw.githubusercontent.com/ismayc/olympic-moderndive-data/main/athlete_events_through_2026.csv"

df = pd.read_csv(url)

print(df.shape)

(315094, 15)

## Inspeccion Inicial

In [68]:
df.head()

      ID                        Name Sex   Age  Height  Weight           Team  NOC        Games  Year  Season    City      Sport                         Event   Medal
0  12068        Arthur Charles Blake   M  24.0     NaN     NaN  United States  USA  1896 Summer  1896  Summer  Athina  Athletics  Athletics Men's 1,500 metres  Silver
1  35094              Angelos Fetsis   M   NaN     NaN     NaN         Greece  GRE  1896 Summer  1896  Summer  Athina  Athletics  Athletics Men's 1,500 metres     NaN
2  35698  Edwin Harold "Teddy" Flack   M  22.0     NaN     NaN      Australia  AUS  1896 Summer  1896  Summer  Athina  Athletics  Athletics Men's 1,500 metres    Gold
3  38123                  Carl Galle   M  23.0   154.0    45.0        Germany  GER  1896 Summer  1896  Summer  Athina  Athletics  Athletics Men's 1,500 metres     NaN
4  41160        Dimitrios P. Golemis   M  21.0     NaN     NaN         Greece  GRE  1896 Summer  1896  Summer  Athina  Athletics  Athletics Men's 1,500 metres     NaN

In [69]:
df["Games"].unique()

array(['1896 Summer', '1900 Summer', '1904 Summer', '1906 Summer', '1908 Summer', '1912 Summer', '1920 Summer', '1924 Summer', '1924 Winter', '1928 Summer', '1928 Winter', '1932 Summer', '1932 Winter', '1936 Summer', '1936 Winter', '1948 Summer', '1948 Winter', '1952 Summer', '1952 Winter', '1956 Summer', '1956 Winter', '1960 Summer', '1960 Winter', '1964 Summer', '1964 Winter', '1968 Summer', '1968 Winter', '1972 Summer', '1972 Winter', '1976 Summer', '1976 Winter', '1980 Summer',
       '1980 Winter', '1984 Summer', '1984 Winter', '1988 Summer', '1988 Winter', '1992 Summer', '1992 Winter', '1994 Winter', '1996 Summer', '1998 Winter', '2000 Summer', '2002 Winter', '2004 Summer', '2006 Winter', '2008 Summer', '2010 Winter', '2012 Summer', '2014 Winter', '2016 Summer', '2018 Winter', '2020 Summer', '2022 Winter', '2024 Summer', '2026 Winter'], dtype=object)

In [70]:
print("Dimensiones del Dataframe->", df.shape, "\n")
print("Columnas del Dataframe:")
for x in range(len(df.columns)):
  print(f"Columna {x}:", df.columns[x])

Dimensiones del Dataframe-> (315094, 15)

Columnas del Dataframe:
Columna 0: ID
Columna 1: Name
Columna 2: Sex
Columna 3: Age
Columna 4: Height
Columna 5: Weight
Columna 6: Team
Columna 7: NOC
Columna 8: Games
Columna 9: Year
Columna 10: Season
Columna 11: City
Columna 12: Sport
Columna 13: Event
Columna 14: Medal

In [71]:
df_original = df.copy()

In [72]:
df = df.rename(columns={
    "ID": "id",
    "Name": "nombre",
    "Sex": "sexo",
    "Age": "edad",
    "Height": "altura_cm",
    "Weight": "peso_kg",
    "Team": "equipo",
    "NOC": "noc",
    "Games": "juegos",
    "Year": "anio",
    "Season": "temporada",
    "City": "ciudad",
    "Sport": "deporte",
    "Event": "evento",
    "Medal": "medalla"
})

## Filtro 1992-2026

In [73]:
# Evaluar el impacto del recorte temporal desde 1992
total_registros = len(df)
registros_desde_1992 = len(df[df["anio"] >= 1992])

# Identificar las ediciones y temporadas conservadas
ediciones_desde_1992 = (
    df[df["anio"] >= 1992][["juegos", "temporada"]]
    .drop_duplicates()
)

# Mostrar el impacto del recorte
print("Registros totales:", total_registros)
print("Registros desde 1992:", registros_desde_1992)

print(
    "Porcentaje conservado:",
    round(registros_desde_1992 / total_registros * 100, 2),
    "%"
)

print("\nEdiciones desde 1992:")
print(ediciones_desde_1992["temporada"].value_counts())
print("Total de ediciones:", len(ediciones_desde_1992))

Registros totales: 315094
Registros desde 1992: 166194
Porcentaje conservado: 52.74 %

Ediciones desde 1992:
temporada
Winter    10
Summer     9
Name: count, dtype: int64
Total de ediciones: 19

In [74]:
# Filtrar el DataFrame desde 1992
df = df[df["anio"] >= 1992].copy()

In [75]:
# Crear una tabla con las ediciones olímpicas del período analizado
ediciones = df[["juegos", "anio", "temporada"]]

ediciones = ediciones.drop_duplicates()

ediciones = ediciones.sort_values(["anio", "temporada"])

ediciones

             juegos  anio temporada
148900  1992 Summer  1992    Summer
161877  1992 Winter  1992    Winter
165313  1994 Winter  1994    Winter
168473  1996 Summer  1996    Summer
182253  1998 Winter  1998    Winter
185858  2000 Summer  2000    Summer
199679  2002 Winter  2002    Winter
203788  2004 Summer  2004    Summer
217231  2006 Winter  2006    Winter
221613  2008 Summer  2008    Summer
235215  2010 Winter  2010    Winter
239617  2012 Summer  2012    Summer
252537  2014 Winter  2014    Winter
257428  2016 Summer  2016    Summer
271116  2018 Winter  2018    Winter
276235  2020 Summer  2020    Summer
290770  2022 Winter  2022    Winter
296019  2024 Summer  2024    Summer
309679  2026 Winter  2026    Winter

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 166194 entries, 148900 to 315093
Data columns (total 15 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         166194 non-null  int64
 1   nombre     166194 non-null  object
 2   sexo       166194 non-null  object
 3   edad       166123 non-null  float64
 4   altura_cm  138904 non-null  float64
 5   peso_kg    135679 non-null  float64
 6   equipo     156100 non-null  object
 7   noc        156100 non-null  object
 8   juegos     166194 non-null  object
 9   anio       166194 non-null  int64
 10  temporada  166194 non-null  object
 11  ciudad     166194 non-null  object
 12  deporte    166194 non-null  object
 13  evento     166194 non-null  object
 14  medalla    21096 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 20.3+ MB

## Valores Nulos

In [77]:
# Verificar la cantidad de valores nulos por columna
df.isnull().sum()

id                0
nombre            0
sexo              0
edad             71
altura_cm     27290
peso_kg       30515
equipo        10094
noc           10094
juegos            0
anio              0
temporada         0
ciudad            0
deporte           0
evento            0
medalla      145098
dtype: int64

In [78]:
# Cantidad y porcentaje de valores nulos por columna
cantidad_nulos = df.isnull().sum()

porcentaje_nulos = (cantidad_nulos / len(df)) * 100

nulos = pd.DataFrame({"cantidad_nulos": cantidad_nulos,"porcentaje_nulos": porcentaje_nulos.round(2)})

nulos

           cantidad_nulos  porcentaje_nulos
id                      0              0.00
nombre                  0              0.00
sexo                    0              0.00
edad                   71              0.04
altura_cm           27290             16.42
peso_kg             30515             18.36
equipo              10094              6.07
noc                 10094              6.07
juegos                  0              0.00
anio                    0              0.00
temporada               0              0.00
ciudad                  0              0.00
deporte                 0              0.00
evento                  0              0.00
medalla            145098             87.31

### Tratamiento de NOC

In [79]:
# Filtrar los registros con valores nulos en NOC
noc_nulos = df[df["noc"].isnull()].copy()
noc_nulos.shape

(10094, 15)

In [80]:
# Contar los NOC nulos por año
cantidad_por_anio = noc_nulos["anio"].value_counts()

# Ordenar los años de menor a mayor
cantidad_por_anio = cantidad_por_anio.sort_index()

cantidad_por_anio

anio
2018    1081
2020    3329
2022    1204
2024    3178
2026    1302
Name: count, dtype: int64

In [81]:
# Obtener los IDs de atletas que tienen un NOC conocido
ids_con_noc = df[df["noc"].notnull()]["id"].unique()

# Verificar si los atletas con NOC nulo aparecen en otros registros con NOC conocido
noc_nulos["id"].isin(ids_con_noc).value_counts()

id
True     6248
False    3846
Name: count, dtype: int64

In [82]:
# Trabajar solamente con los registros que tienen NOC conocido
datos_con_noc = df[df["noc"].notnull()]

# Contar cuántos NOC diferentes tiene asociado cada atleta
noc_por_id = datos_con_noc.groupby("id")["noc"].nunique()

# Ver cuántos atletas tienen 1, 2, 3... NOC diferentes
noc_por_id.value_counts()

noc
1    79539
2      871
3       24
Name: count, dtype: int64

In [83]:
# Obtener los IDs de atletas asociados a un único NOC
ids_noc_unico = noc_por_id[noc_por_id == 1].index

# Ver cuántos registros con NOC nulo pertenecen a atletas con un único NOC conocido
noc_nulos["id"].isin(ids_noc_unico).value_counts()

id
True     6190
False    3904
Name: count, dtype: int64

In [84]:
# Identificar atletas que tienen un único NOC conocido
condicion_id = df["id"].isin(ids_noc_unico)

# Identificar registros donde el NOC no es nulo
condicion_noc = df["noc"].notnull()

# Filtrar las filas que cumplen ambas condiciones
noc_unico = df[condicion_id & condicion_noc]

# Conservar solamente las columnas necesarias
noc_unico = noc_unico[["id", "noc"]]

noc_unico.head()

           id  noc
148900   3656  MEX
148901   8174  USA
148902  16870  MEX
148903  17162  GUM
148904  17232  CAN

In [85]:
# Eliminar combinaciones repetidas de ID y NOC
noc_unico = noc_unico.drop_duplicates()
noc_unico.head(10)

           id  noc
148900   3656  MEX
148901   8174  USA
148902  16870  MEX
148903  17162  GUM
148904  17232  CAN
148905  17816  NED
148906  25130  IND
148907  28056  ITA
148908  30909  BRA
148909  31417  TUR

In [86]:
noc_unico.shape

(79539, 2)

In [87]:
# Crear una correspondencia entre cada ID y su único NOC conocido
mapa_noc = noc_unico.set_index("id")["noc"]

# Completar los NOC faltantes cuando existe una correspondencia segura por ID
df["noc"] = df["noc"].fillna(df["id"].map(mapa_noc))

# Verificar cuántos NOC nulos permanecen después de la recuperación
print("Valores nulos de NOC->",df["noc"].isnull().sum())

Valores nulos de NOC-> 3904

### Tratamiento de MEDALLA

In [88]:
# Ver los valores presentes en la columna medalla
df["medalla"].value_counts(dropna=False)

medalla
NaN       145098
Bronze      7264
Gold        6935
Silver      6897
Name: count, dtype: int64

## Valores Duplicados

In [89]:
# Verificar si existen filas completamente duplicadas
df.duplicated().sum()

np.int64(0)

# Análisis Exploratorio de Datos

## Hipótesis 1
Existe una relación positiva entre la cantidad de atletas que presenta una delegación y la cantidad de medallas que obtiene. Esta relación puede ser diferente entre los Juegos de Verano y los Juegos de Invierno.

**Pregunta de análisis:** ¿Existe una relación entre la cantidad de atletas que presenta una delegación y la cantidad de medallas que obtiene? ¿Esta relación es diferente entre Juegos de Verano e Invierno?

In [90]:
# Conservar registros con NOC(Nacionalidad) conocida
datos_h1 = df[df["noc"].notnull()].copy()

In [91]:
# Agrupar por edición y delegación y contar atletas diferentes
# Indicamos que queremos trabajar con el ID, ya que este puede
# participar de mas de un evento
atletas_h1 = datos_h1.groupby(["juegos", "anio", "temporada", "noc"])["id"].nunique()

# Convertir el resultado nuevamente en DataFrame
atletas_h1 = atletas_h1.reset_index()

# Renombrar la columna con el número de atletas
atletas_h1 = atletas_h1.rename(columns={"id": "cantidad_atletas"})

atletas_h1.head(10)

        juegos  anio temporada  noc  cantidad_atletas
0  1992 Summer  1992    Summer  AHO                 4
1  1992 Summer  1992    Summer  ALB                 7
2  1992 Summer  1992    Summer  ALG                35
3  1992 Summer  1992    Summer  AND                 8
4  1992 Summer  1992    Summer  ANG                28
5  1992 Summer  1992    Summer  ANT                13
6  1992 Summer  1992    Summer  ARG                84
7  1992 Summer  1992    Summer  ARU                 5
8  1992 Summer  1992    Summer  ASA                 3
9  1992 Summer  1992    Summer  AUS               279

In [92]:
# Conservar solamente los registros donde se obtuvo una medalla
medallas_h1 = datos_h1[datos_h1["medalla"].notnull()].copy()

medallas_h1.head()

            id                 nombre sexo  edad  altura_cm  peso_kg         equipo  noc       juegos  anio temporada     ciudad  deporte                    evento medalla
148915   35971          Sbastien Flte    M  20.0      170.0     58.0         France  FRA  1992 Summer  1992    Summer  Barcelona  Archery  Archery Men's Individual    Gold
148929   54545         Jeong Jae-Heon    M  18.0        NaN      NaN    South Korea  KOR  1992 Summer  1992    Summer  Barcelona  Archery  Archery Men's Individual  Silver
148963  119320     Simon Duncan Terry    M  18.0      180.0    100.0  Great Britain  GBR  1992 Summer  1992    Summer  Barcelona  Archery  Archery Men's Individual  Bronze
148986   33859      Ismo Kalevi Falck    M  25.0      172.0     70.5        Finland  FIN  1992 Summer  1992    Summer  Barcelona  Archery        Archery Men's Team  Silver
148992   45048  Steven Leslie Hallard    M  27.0      188.0     84.0  Great Britain  GBR  1992 Summer  1992    Summer  Barcelona  Archery        Archery Men's Team  Bronze

In [93]:
# Evitar contar varias veces una misma medalla obtenida por una delegación en un evento
medallas_unicas_h1 = medallas_h1.drop_duplicates(subset=["juegos", "noc", "evento", "medalla"]).copy()

In [94]:
print("Registros con medalla:", len(medallas_h1))
print("Medallas sin repeticiones de equipo:", len(medallas_unicas_h1))

Registros con medalla: 21096
Medallas sin repeticiones de equipo: 10380

In [95]:
# Contar la cantidad de medallas por delegación y edición
medallas_por_delegacion = medallas_unicas_h1.groupby(
    ["juegos", "anio", "temporada", "noc"]
)["medalla"].count()

medallas_por_delegacion.head(15)

juegos       anio  temporada  noc
1992 Summer  1992  Summer     ALG     2
                              ARG     1
                              AUS    27
                              AUT     2
                              BAH     1
                              BEL     3
                              BRA     3
                              BUL    16
                              CAN    18
                              CHN    53
                              COL     1
                              CRO     3
                              CUB    31
                              DEN     6
                              ESP    22
Name: medalla, dtype: int64

In [96]:
# Convertir el resultado nuevamente en DataFrame
medallas_por_delegacion = medallas_por_delegacion.reset_index()

In [97]:
# Renombrar la columna con el número de medallas
medallas_por_delegacion = medallas_por_delegacion.rename(
    columns={"medalla": "cantidad_medallas"}
)

medallas_por_delegacion.head(10)

        juegos  anio temporada  noc  cantidad_medallas
0  1992 Summer  1992    Summer  ALG                  2
1  1992 Summer  1992    Summer  ARG                  1
2  1992 Summer  1992    Summer  AUS                 27
3  1992 Summer  1992    Summer  AUT                  2
4  1992 Summer  1992    Summer  BAH                  1
5  1992 Summer  1992    Summer  BEL                  3
6  1992 Summer  1992    Summer  BRA                  3
7  1992 Summer  1992    Summer  BUL                 16
8  1992 Summer  1992    Summer  CAN                 18
9  1992 Summer  1992    Summer  CHN                 53

In [98]:
# Unir la cantidad de atletas y la cantidad de medallas
# Obtenidas por cada pais en determinada edicion
h1 = atletas_h1.merge(medallas_por_delegacion, on=["juegos", "anio", "temporada", "noc"], how="left")
h1.head(10)

        juegos  anio temporada  noc  cantidad_atletas  cantidad_medallas
0  1992 Summer  1992    Summer  AHO                 4                NaN
1  1992 Summer  1992    Summer  ALB                 7                NaN
2  1992 Summer  1992    Summer  ALG                35                2.0
3  1992 Summer  1992    Summer  AND                 8                NaN
4  1992 Summer  1992    Summer  ANG                28                NaN
5  1992 Summer  1992    Summer  ANT                13                NaN
6  1992 Summer  1992    Summer  ARG                84                1.0
7  1992 Summer  1992    Summer  ARU                 5                NaN
8  1992 Summer  1992    Summer  ASA                 3                NaN
9  1992 Summer  1992    Summer  AUS               279               27.0

In [99]:
# Ver cuántos valores nulos quedaron en cantidad_medallas
h1["cantidad_medallas"].isnull().sum()

np.int64(1613)

In [100]:
# Reemplazar los valores nulos por 0 medallas
h1["cantidad_medallas"] = h1["cantidad_medallas"].fillna(0)

In [101]:
# Convertir la cantidad de medallas a números enteros
h1["cantidad_medallas"] = h1["cantidad_medallas"].astype(int)

In [102]:
h1.head(10)

        juegos  anio temporada  noc  cantidad_atletas  cantidad_medallas
0  1992 Summer  1992    Summer  AHO                 4                  0
1  1992 Summer  1992    Summer  ALB                 7                  0
2  1992 Summer  1992    Summer  ALG                35                  2
3  1992 Summer  1992    Summer  AND                 8                  0
4  1992 Summer  1992    Summer  ANG                28                  0
5  1992 Summer  1992    Summer  ANT                13                  0
6  1992 Summer  1992    Summer  ARG                84                  1
7  1992 Summer  1992    Summer  ARU                 5                  0
8  1992 Summer  1992    Summer  ASA                 3                  0
9  1992 Summer  1992    Summer  AUS               279                 27

In [103]:
# Resumen estadístico de las variables de la H1
h1[["cantidad_atletas", "cantidad_medallas"]].describe()

       cantidad_atletas  cantidad_medallas
count       2603.000000        2603.000000
mean          45.023819           3.987706
std           83.193611          11.085123
min            1.000000           0.000000
25%            4.000000           0.000000
50%            9.000000           0.000000
75%           47.000000           3.000000
max          648.000000         121.000000

In [104]:
# Calcular la correlación entre cantidad de atletas y cantidad de medallas
correlacion = h1["cantidad_atletas"].corr(h1["cantidad_medallas"])

print("Correlación atletas-medallas:", correlacion)

Correlación atletas-medallas: 0.8799191713418314

La correlación obtenida fue aproximadamente 0,88, lo que indica una relación positiva fuerte: en general, las delegaciones con mayor cantidad de atletas tienden a obtener más medallas.

In [105]:
# Separar los datos de Juegos de Verano
h1_verano = h1[h1["temporada"] == "Summer"]

# Separar los datos de Juegos de Invierno
h1_invierno = h1[h1["temporada"] == "Winter"]

In [106]:
# Calcular la correlación para cada temporada
correlacion_verano = h1_verano["cantidad_atletas"].corr(
    h1_verano["cantidad_medallas"]
)

correlacion_invierno = h1_invierno["cantidad_atletas"].corr(
    h1_invierno["cantidad_medallas"]
)

print("Correlación en Juegos de Verano:", correlacion_verano)
print("Correlación en Juegos de Invierno:", correlacion_invierno)

Correlación en Juegos de Verano: 0.8848525105742368
Correlación en Juegos de Invierno: 0.8415246861495838

In [107]:
# Gráfico de dispersión con distribuciones marginales
fig = px.scatter(
    h1,
    x="cantidad_atletas",          # Eje X: cantidad de atletas
    y="cantidad_medallas",         # Eje Y: cantidad de medallas
    color="temporada",             # Diferenciar Summer y Winter por color

    # El tamaño del punto refuerza visualmente la cantidad de atletas
    size="cantidad_atletas",
    size_max=15,

    # Gráficos marginales
    # Arriba: boxplot de atletas
    # Derecha: histograma de medallas
    marginal_x="box",
    marginal_y="histogram",

    # Agregar línea de tendencia lineal
    trendline="ols",

    # Información que aparece al pasar el mouse
    hover_name="noc",
    hover_data={
        "juegos": True,
        "anio": True,
        "cantidad_atletas": True,
        "cantidad_medallas": True,
        "temporada": False
    },

    # Estilo visual del gráfico
    template="plotly_dark",

    # Colores asignados a cada temporada
    color_discrete_map={
        "Summer": "orange",
        "Winter": "deepskyblue"
    },

    # Etiquetas de ejes y variables
    labels={
        "cantidad_atletas": "Cantidad de atletas",
        "cantidad_medallas": "Cantidad de medallas",
        "temporada": "Temporada",
        "juegos": "Edición",
        "anio": "Año"
    },

    # Transparencia de los puntos
    opacity=0.65
)

# Agregar líneas guía que siguen al cursor
fig.update_xaxes(
    showspikes=True,
    spikemode="across",
    spikesnap="cursor"
)

fig.update_yaxes(
    showspikes=True,
    spikemode="across",
    spikesnap="cursor"
)

# Configurar fondo, hover y título
fig.update_layout(
    hovermode="closest",
    paper_bgcolor="black",
    plot_bgcolor="black",

    title={
        "text": "<b>📈 Relación entre cantidad de atletas y medallas</b>",
        "x": 0.5,                  # Centrar el título
        "xanchor": "center",
        "font": {
            "size": 22             # Tamaño del título
        }
    }
)

# Mostrar el gráfico interactivo
fig.show(
    config={
        "scrollZoom": True,        # Permitir zoom con la rueda del mouse
        "displaylogo": False       # Ocultar logo de Plotly
    }
)

In [108]:
# Gráfico de dispersión animado
fig_animado = px.scatter(
    h1,
    x="cantidad_atletas",          # Eje X: cantidad de atletas
    y="cantidad_medallas",         # Eje Y: cantidad de medallas
    color="temporada",             # Diferenciar Summer y Winter por color

    # Crear la animación usando el año como fotograma
    animation_frame="anio",

    # Información que aparece al pasar el mouse
    hover_name="noc",
    hover_data=["juegos"],

    # Estilo visual del gráfico
    template="plotly_dark",

    # Colores elegidos para cada temporada
    color_discrete_map={
        "Summer": "orange",
        "Winter": "deepskyblue"
    },

    # Etiquetas de ejes y variables
    labels={
        "cantidad_atletas": "Cantidad de atletas",
        "cantidad_medallas": "Cantidad de medallas",
        "temporada": "Temporada",
        "anio": "Año"
    },

    # Mantener los mismos límites en todos los años
    # para poder comparar mejor la evolución
    range_x=[0, h1["cantidad_atletas"].max() + 50],
    range_y=[0, h1["cantidad_medallas"].max() + 10]
)

# Ajustar la apariencia de los puntos
fig_animado.update_traces(
    marker=dict(
        size=9,        # Tamaño de los puntos
        opacity=0.7    # Transparencia
    )
)

# Configurar fondo y título
fig_animado.update_layout(
    paper_bgcolor="black",
    plot_bgcolor="black",

    title={
        "text": "<b>▶️ Evolución de atletas y medallas por edición olímpica</b>",
        "x": 0.5,                 # Centrar el título
        "xanchor": "center",
        "font": {
            "size": 22            # Tamaño del título
        }
    }
)

# Mostrar el gráfico interactivo
fig_animado.show(
    config={
        "scrollZoom": True,       # Permitir zoom con la rueda del mouse
        "displaylogo": False      # Ocultar logo de Plotly
    }
)

In [109]:
# Mapa de calor de densidad
fig = px.density_heatmap(
    h1,
    x="cantidad_atletas",          # Eje X: cantidad de atletas
    y="cantidad_medallas",         # Eje Y: cantidad de medallas
    facet_col="temporada",         # Separar el gráfico en Summer y Winter

    # Definir la cantidad de intervalos en cada eje
    # Menos celdas ayuda a concentrar mejor los casos
    nbinsx=15,
    nbinsy=15,

    # El color representa la cantidad de observaciones por celda
    histfunc="count",

    # Estilo visual del gráfico
    template="plotly_dark",
    color_continuous_scale="Viridis",

    # Limitar la escala de color para mejorar el contraste visual
    range_color=[0, 25],

    # Etiquetas de los ejes y la variable de separación
    labels={
        "cantidad_atletas": "Cantidad de atletas",
        "cantidad_medallas": "Cantidad de medallas",
        "temporada": "Temporada"
    }
)

# Configurar el título y la barra de colores
fig.update_layout(
    title={
        "text": "<b>🌡️ Concentración de delegaciones según cantidad de atletas y medallas</b>",
        "x": 0.5,                  # Centrar el título
        "xanchor": "center",
        "font": {"size": 22}       # Tamaño del título
    },

    coloraxis_colorbar={
        "title": "Cantidad<br>de casos"   # Título de la barra de colores
    }
)

# Mostrar el gráfico con zoom y sin el logo de Plotly
fig.show(
    config={
        "scrollZoom": True,
        "displaylogo": False
    }
)

Los resultados muestran una correlación positiva fuerte entre la cantidad de atletas y la cantidad de medallas. La relación se observa tanto en los Juegos de Verano (r ≈ 0,88) como en los Juegos de Invierno (r ≈ 0,84), siendo ligeramente mayor en los Juegos de Verano.

### Conclusion de hipótesis 1
A partir de los resultados obtenidos y de los gráficos realizados, los datos respaldan la existencia de una relación positiva fuerte entre la cantidad de atletas participantes y la cantidad de medallas obtenidas por país, con una correlación de 0,88. Esto indica que, en términos generales, los países que cuentan con una mayor cantidad de atletas tienden también a obtener una mayor cantidad de medallas.

Este comportamiento se observa tanto en los Juegos Olímpicos de Verano como en los de Invierno, aunque estos últimos presentan una menor cantidad de atletas y delegaciones participantes. Sin embargo, al comparar ambos tipos de Juegos, no se observa una diferencia marcada en el patrón general de la relación.

Por lo tanto, la primera parte de la hipótesis encuentra respaldo en los datos, mientras que la segunda parte no se ve respaldada. La hipótesis planteaba que la relación presentaría diferencias entre los Juegos de Verano y los de Invierno, pero los resultados muestran un comportamiento similar en ambas temporadas.

## Hipótesis 2

Los países que obtienen una mayor cantidad total de medallas no necesariamente presentan una mayor eficiencia en relación con la cantidad de atletas participantes.

**Pregunta de análisis:** ¿Qué países presentan una mayor cantidad de medallas en relación con la cantidad de atletas participantes?

In [110]:
#Filtramos solo filas con medalla y eliminamos duplicados por evento,
# año/noc/medalla, con esto logramos que los deportes que se jueguen en
# equipo cuenten como una unica medalla para el pais correspondiente
df_medallas_unicas = df.dropna(subset=['medalla']).drop_duplicates(
    subset=['anio', 'temporada', 'noc', 'evento', 'medalla']
)

#Agrupamos medallas reales ganadas por pais
df_total_medallas = df_medallas_unicas.groupby('noc')['medalla'].count().reset_index(
    name='medallas_reales'
)

#Agrupamos total de atletas unicos por pais
df_total_atletas = df.groupby('noc')['id'].nunique().reset_index(
    name='total_atletas'
)

#Unimos ambos DataFrames para poder calcular la eficiencia
df_h2 = pd.merge(df_total_atletas,
                 df_total_medallas,
                 on='noc',
                 how='left').fillna(0)
df_h2['eficiencia'] = (df_h2['medallas_reales'] / df_h2['total_atletas']).round(4)

#Ordenamos por eficiencia de mayor a menor
df_h2 = df_h2.sort_values(by='eficiencia', ascending=False)

#Verificamos que lo que hicimos es correcto
df_h2.head(10)

     noc  total_atletas  medallas_reales  eficiencia
146  NOR            997            308.0      0.3089
65   ETH            189             51.0      0.2698
167  RUS           2258            576.0      0.2551
40   CHN           2737            694.0      0.2536
208  USA           4864           1150.0      0.2364
100  JAM            301             69.0      0.2292
14   AZE            257             58.0      0.2257
66   EUN            604            135.0      0.2235
51   CUB            826            184.0      0.2228
75   GEO            212             47.0      0.2217

In [111]:
#Diseñamos el grafico de dispersion
fig_dispersion = px.scatter(
    df_h2,  #Fuente de datos
    x='total_atletas',  #Eje x
    y='medallas_reales',  #Eje y
    size='eficiencia',  #El tamaño del punto depende del valor de eficiencia
    color='eficiencia', #El punto cambia de color segun el valor
    hover_name='noc', #Mostrar NOC cuando pasamos el mouse
    hover_data={  #Configurar info a mostrar
        'total_atletas': ':,',
        'medallas_reales': ':,',
        'eficiencia': ':.3f'
    },
    title='<b>Eficiencia entre cantidad de<br>atletas y medallas obtenidas</b>',
    labels={
        'total_atletas': 'Total de Atletas',
        'medallas_reales': 'Medallas obtenidas',
        'eficiencia': 'Eficiencia'
    },
    color_continuous_scale='Viridis',
    template='plotly_dark',
    size_max=15, #Tamaño de los puntos de datos
    trendline="ols", #Recta de referencia
    trendline_color_override="rgba(200, 162, 200, 0.5)" #Color de recta y transparencia
)

#Centramos el titulo del grafico
fig_dispersion.update_layout(title_x=0.5)

# Agregamos líneas guía al pasar por los puntos
# Eje x
fig_dispersion.update_xaxes(
    showspikes=True,
    spikemode="across",
    spikesnap="cursor"
)

#Eje y
fig_dispersion.update_yaxes(
    showspikes=True,
    spikemode="across",
    spikesnap="cursor"
)

fig_dispersion.show(
    config={  #Hacer zoom con scroll del mouse
        "scrollZoom": True,
        "displaylogo": False
    }
    )

In [112]:
#Creamos un DF con la columna tamano_delegacion que nos indicara
# si la delegacion de cada pais es Pequeña, Mediana o Grande
df_h2['tamano_delegacion'] = pd.qcut(
    df_h2['total_atletas'],
    q=3,
    labels=['Pequeña', 'Mediana', 'Grande']
)

# Verificamos la cantidad de países que contiene cada grupo
df_h2['tamano_delegacion'].value_counts()

tamano_delegacion
Pequeña    73
Grande     73
Mediana    72
Name: count, dtype: int64

In [113]:
#Dividimos las delegaciones por tamaño
#Calculamos media y mediana de cada grupo
eficiencia_por_tamano = (
    df_h2.groupby('tamano_delegacion', observed=True)['eficiencia']
    .agg(['mean', 'median', 'count'])
    .reset_index()
)

eficiencia_por_tamano

  tamano_delegacion      mean  median  count
0           Pequeña  0.013238  0.0000     73
1           Mediana  0.035028  0.0193     72
2            Grande  0.114530  0.1002     73

In [114]:
#Creacion grafico de barras
fig_eficiencia = px.bar(
    eficiencia_por_tamano,
    x='tamano_delegacion',
    y='mean',
    text='mean',
    title='<b>🏅 Eficiencia promedio según tamaño de la delegación</b>',
    labels={
        'tamano_delegacion': 'Tamaño de la delegación',
        'mean': 'Eficiencia promedio (medallas por atleta)'
    },
    template='plotly_dark'  #Fondo oscuro
)

#Estilo y efectos

fig_eficiencia.update_traces( #Modificar caracteristicas visuales
    texttemplate='%{text:.4f}',
    textposition='outside', #Posicion de valor numerico
    marker_color='#D4AF37', #Color de barras
    marker_line_color='white',  #Color borde barras
    marker_line_width=1.2,  #Grosor del borde
    hovertemplate=(
        '<b>%{x}</b><br>'
        'Eficiencia promedio: <b>%{y:.4f}</b><br>'
        '<extra></extra>'
    )
)

# Línea de referencia

#Calculamos promedio de eficiencia general de los paises
eficiencia_general = df_h2['eficiencia'].mean()

#Agregamos una línea horizontal en el grafico
fig_eficiencia.add_hline(
    y=eficiencia_general, #Altura de posicion
    line_dash='dash', #Linea puntuada
    line_width=2, #Grosor de linea
    line_color='#FF6B6B', #Color de linea
    annotation_text=f'Promedio general: {eficiencia_general:.4f}',#Texto de la linea
    annotation_position='top left', #Posicion de etiqueta
    annotation_font=dict( #Tamaño y color de la anotacion
        color='#FF6B6B',
        size=12
    )
)

# Diseño

fig_eficiencia.update_layout( #Modificamos aspecto del grafico
    title=dict(
        text='<b>🏅 Eficiencia promedio según tamaño de la delegación</b>',
        x=0.5,  #Titulo centrado
        xanchor='center',
        font=dict(size=22, color='white') #Tamaño y color
    ),

    paper_bgcolor='#111111',  #Color de fondo exterior de grafico
    plot_bgcolor='#111111', #Color de zona de grafico

    height=600, #Tamaño grafico

    margin=dict(  #Margenes
        t=120,
        b=90,
        l=80,
        r=50
    ),

    xaxis=dict( #Configuracion eje x
        title='Tamaño de la delegación',
        title_font=dict(
            color='white',
            size=14
        ),
        tickfont=dict(
            color='#D9D9D9',
            size=13
        ),
        gridcolor='#292929'
    ),

    yaxis=dict( #Configuracion eje y
        title='Eficiencia promedio (medallas por atleta)',
        title_font=dict(
            color='#D4AF37',
            size=14
        ),
        tickfont=dict(
            color='#D9D9D9'
        ),
        gridcolor='#292929',
        rangemode='tozero'
    ),

    hoverlabel=dict(  #Configuracion de cuadro que aparece al pasar mouse
        bgcolor='#1C1C1C',  #Color fondo
        bordercolor='#D4AF37',  #Color borde
        font=dict(
            color='white',
            size=14
        )
    )
)

# Interactividad

fig_eficiencia.update_xaxes(  #Configura eje x
    showspikes=True,  #Mostrar lineas de seguimiento
    spikemode='across', #La linea atraviesa el area del grafico
    spikesnap='cursor'  #La linea sigue al cursor
)

fig_eficiencia.update_yaxes(  #Configura eje y
    showspikes=True,
    spikemode='across',
    spikesnap='cursor'
)

fig_eficiencia.show(
    config={  #Hacer zoom con scroll del mouse
        'scrollZoom': True,
        'displaylogo': False
    }
)

###Conclusion de hipótesis 2

Considerando los resultados obtenidos a través de los gráficos y el análisis de los datos, podemos observar varios aspectos relevantes. En primer lugar, no resulta suficiente analizar únicamente la eficiencia promedio de cada país, ya que las delegaciones presentan tamaños muy diferentes. Una delegación pequeña puede obtener una eficiencia elevada a partir de una cantidad relativamente reducida de medallas, mientras que una delegación mucho más numerosa puede obtener una mayor cantidad total de medallas pero presentar una eficiencia proporcionalmente menor.

Por este motivo, decidimos dividir los países según el tamaño de sus delegaciones y analizar la eficiencia dentro de cada grupo. Los resultados muestran una tendencia clara: al igual que observamos en la hipótesis anterior, las delegaciones con una mayor cantidad de atletas tienden a obtener una mayor cantidad total de medallas. Sin embargo, también observamos diferencias en la eficiencia según el tamaño de la delegación. En nuestro análisis, las delegaciones grandes presentaron una eficiencia promedio superior a las medianas y pequeñas.

Por lo tanto, los resultados respaldan la hipótesis planteada, ya que la cantidad total de medallas y la eficiencia representan medidas diferentes del desempeño de una delegación. Una mayor cantidad de medallas no implica necesariamente una mayor eficiencia, por lo que resulta necesario considerar ambas variables para realizar una comparación más completa.

## Hipótesis 3

Los países anfitriones obtienen, en promedio, una mayor cantidad de medallas cuando compiten como locales que en otras ediciones en las que participan sin ser anfitriones.

**Pregunta de análisis:** ¿Los países anfitriones obtienen más medallas cuando compiten como locales que en otras ediciones?

In [115]:
# País anfitrión de cada edición olímpica del período analizado
# distinguimos si son juegos de invierno o verano

sedes_olimpicas = {
    (1992, 'Summer'): 'ESP',
    (1994, 'Winter'): 'NOR',
    (1996, 'Summer'): 'USA',
    (1998, 'Winter'): 'JPN',
    (2000, 'Summer'): 'AUS',
    (2002, 'Winter'): 'USA',
    (2004, 'Summer'): 'GRE',
    (2006, 'Winter'): 'ITA',
    (2008, 'Summer'): 'CHN',
    (2010, 'Winter'): 'CAN',
    (2012, 'Summer'): 'GBR',
    (2014, 'Winter'): 'RUS',
    (2016, 'Summer'): 'BRA',
    (2018, 'Winter'): 'KOR',
    (2020, 'Summer'): 'JPN',
    (2022, 'Winter'): 'CHN',
    (2024, 'Summer'): 'FRA',
    (2026, 'Winter'): 'ITA'
}

In [116]:
# Cantidad de atletas únicos por país y edición

df_atletas_h3 = (
    df.groupby(['anio', 'temporada', 'noc'])['id']
    .nunique()
    .reset_index(name='total_atletas')
)

In [117]:
# Filtramos únicamente los registros que tienen medalla
df_medallas_h3 = df.dropna(subset=['medalla'])

# Eliminamos duplicados para que las medallas de equipo
# cuenten una sola vez por país, evento y edición
df_medallas_h3 = df_medallas_h3.drop_duplicates(
    subset=['anio', 'temporada', 'noc', 'evento', 'medalla']
)

# Contamos las medallas por país y edición
df_total_medallas_h3 = (
    df_medallas_h3
    .groupby(['anio', 'temporada', 'noc'])['medalla']
    .count()
    .reset_index(name='medallas_reales')
)

In [118]:
# Unimos atletas y medallas
df_h3 = pd.merge(
    df_atletas_h3,
    df_total_medallas_h3,
    on=['anio', 'temporada', 'noc'],
    how='left'
)

# Los países que no obtuvieron medallas reciben valor 0
df_h3['medallas_reales'] = df_h3['medallas_reales'].fillna(0)

In [119]:
# Identificamos el país anfitrión de cada edición
df_h3['pais_anfitrion'] = df_h3.apply(
    lambda fila: sedes_olimpicas.get(
        (fila['anio'], fila['temporada'])
    ),
    axis=1
)

# Indicamos si el país analizado era el anfitrión
df_h3['es_anfitrion'] = (
    df_h3['noc'] == df_h3['pais_anfitrion']
)

In [120]:
# Identificamos los países que fueron anfitriones
paises_anfitriones = df_h3.loc[
    df_h3['es_anfitrion'],
    'noc'
].unique()

# Nos quedamos únicamente con esos países
df_h3_comparacion = df_h3[
    df_h3['noc'].isin(paises_anfitriones)].copy()

In [121]:
#Calculamos promedio
promedio_h3 = (
    df_h3_comparacion
    .groupby('es_anfitrion')['medallas_reales']
    .mean()
    .reset_index()
)

promedio_h3['condicion'] = promedio_h3['es_anfitrion'].map({
    True: 'Como anfitrión',
    False: 'Sin ser anfitrión'
})

promedio_h3

   es_anfitrion  medallas_reales          condicion
0         False        20.652893  Sin ser anfitrión
1          True        36.888889     Como anfitrión

In [122]:
fig_h3 = px.bar(
    promedio_h3,
    x='condicion',
    y='medallas_reales',
    text='medallas_reales',
    color='condicion',
    color_discrete_map={
        'Como anfitrión': '#D4AF37',
        'Sin ser anfitrión': '#4E79A7'
    },
    title='<b>🏠 El efecto de competir como local</b>',
    labels={
        'condicion': 'Condición',
        'medallas_reales': 'Promedio de medallas'
    },
    template='plotly_dark'
)

# Barras

fig_h3.update_traces(
    texttemplate='%{text:.2f}',
    textposition='outside',
    marker_line_color='white',
    marker_line_width=1.2,
    hovertemplate=(
        '<b>%{x}</b><br>'
        'Promedio de medallas: <b>%{y:.2f}</b>'
        '<extra></extra>'
    )
)

# Diferencia de promedio de las dos condiciones

diferencia_h3 = (
    promedio_h3.loc[
        promedio_h3['es_anfitrion'] == True,
        'medallas_reales'
    ].iloc[0]
    -
    promedio_h3.loc[
        promedio_h3['es_anfitrion'] == False,
        'medallas_reales'
    ].iloc[0]
)

#Agregamos una anotacion que indica diferencia de promedio
# general cuando un pais es anfitrion o no
fig_h3.add_annotation(
    x=0.5,  #Centrado
    y=max(promedio_h3['medallas_reales']) * 0.65,
    text=f'<b>Δ {diferencia_h3:.2f} medallas</b>',
    showarrow=True, #Agregar flecha a la anotacion
    arrowhead=2,  #Apariencia flecha
    arrowcolor='#FF6B6B', #Color flecha
    font=dict(
        color='#FF6B6B',
        size=15
    ),
    bgcolor='#1C1C1C',  # color fondo anotacion
    bordercolor='#FF6B6B',  #Color borde
    borderwidth=1
)

# Diseño

fig_h3.update_layout(
    title=dict(
        text='<b>🏠 El efecto de competir como local</b>',
        x=0.5,
        xanchor='center',
        font=dict(
            size=23,
            color='white'
        )
    ),

    paper_bgcolor='#111111',
    plot_bgcolor='#111111',

    height=600,

    margin=dict(
        t=120,
        b=90,
        l=80,
        r=50
    ),

    legend=dict(
        title='Condición',
        font=dict(color='#D9D9D9'),
        bgcolor='#1C1C1C',
        bordercolor='#444444',
        borderwidth=1
    ),

    xaxis=dict(
        title='Condición',
        title_font=dict(
            color='white',
            size=14
        ),
        tickfont=dict(
            color='#D9D9D9',
            size=13
        ),
        gridcolor='#292929'
    ),

    yaxis=dict(
        title='Promedio de medallas',
        title_font=dict(
            color='#D4AF37',
            size=14
        ),
        tickfont=dict(
            color='#D9D9D9'
        ),
        gridcolor='#292929',
        rangemode='tozero'
    ),

    hoverlabel=dict(
        bgcolor='#1C1C1C',
        bordercolor='#D4AF37',
        font=dict(
            color='white',
            size=14
        )
    )
)

# Interactividad

fig_h3.update_xaxes(
    showspikes=True,
    spikemode='across',
    spikesnap='cursor'
)

fig_h3.update_yaxes(
    showspikes=True,
    spikemode='across',
    spikesnap='cursor'
)

fig_h3.show(
    config={
        'scrollZoom': True,
        'displaylogo': False
    }
)

In [123]:
# Promedio de medallas de cada país anfitrión
# comparando sus participaciones como local y como no local

comparacion_paises_h3 = (
    df_h3_comparacion
    .groupby(['noc', 'es_anfitrion'])['medallas_reales']
    .mean()
    .reset_index()
)

# Convertimos la condición booleana en texto
comparacion_paises_h3['condicion'] = comparacion_paises_h3['es_anfitrion'].map({
    True: 'Como anfitrión',
    False: 'Sin ser anfitrión'
})

comparacion_paises_h3

    noc  es_anfitrion  medallas_reales          condicion
0   AUS         False        17.944444  Sin ser anfitrión
1   AUS          True        58.000000     Como anfitrión
2   BRA         False         6.111111  Sin ser anfitrión
3   BRA          True        19.000000     Como anfitrión
4   CAN         False        17.944444  Sin ser anfitrión
5   CAN          True        26.000000     Como anfitrión
6   CHN         False        34.294118  Sin ser anfitrión
7   CHN          True        55.500000     Como anfitrión
8   ESP         False         7.277778  Sin ser anfitrión
9   ESP          True        22.000000     Como anfitrión
10  FRA         False        21.166667  Sin ser anfitrión
11  FRA          True        53.000000     Como anfitrión
12  GBR         False        17.333333  Sin ser anfitrión
13  GBR          True        65.000000     Como anfitrión
14  GRE         False         2.500000  Sin ser anfitrión
15  GRE          True        16.000000     Como anfitrión
16  ITA         False        20.470588  Sin ser anfitrión
17  ITA          True        14.500000     Como anfitrión
18  JPN         False        17.882353  Sin ser anfitrión
19  JPN          True        30.000000     Como anfitrión
20  KOR         False        16.388889  Sin ser anfitrión
21  KOR          True        14.000000     Como anfitrión
22  NOR         False        15.833333  Sin ser anfitrión
23  NOR          True        23.000000     Como anfitrión
24  RUS         False        45.250000  Sin ser anfitrión
25  RUS          True        33.000000     Como anfitrión
26  USA         False        59.705882  Sin ser anfitrión
27  USA          True        67.500000     Como anfitrión

In [124]:
# Lista de países anfitriones
#Ordenamos alfabeticamente y unifica repetidos
paises = sorted(comparacion_paises_h3['noc'].unique())

#Crea una objeto Figure
fig_h3_paises = go.Figure()

# Crear una línea para cada país

#Obtiene los datos de cada pais
for pais in paises:

    datos_pais = comparacion_paises_h3[
        comparacion_paises_h3['noc'] == pais
    ].sort_values('es_anfitrion')

# Agregar linea por pais
    fig_h3_paises.add_trace(
        go.Scatter( #Grafico de lineas y puntos
            x=datos_pais['condicion'], #Es o no anfitrion
            y=datos_pais['medallas_reales'],#Promedio medallas
            mode='lines+markers', #Tipo de grafico
            name=pais, #Identificar linea con pais
            line=dict(width=3), #Grosor de linea
            marker=dict(size=11), #Tamaño de los puntos
            hovertemplate=( #Configuracion de info al pasar mouse
                '<b>País: %{fullData.name}</b><br>'
                'Condición: %{x}<br>'
                'Promedio de medallas: %{y:.2f}'
                '<extra></extra>'
            )
        )
    )

# Crear opciones del menú desplegable

#Creamos lista de botones
botones = [
    dict(
        label='🌎 Todos los países',
        method='update', #Actualizar grafico cuando se elija boton
        args=[  #Modificaciones cuando se presione el boton
            {'visible': [True] * len(paises)},
            {'title': '<b>Medallas promedio de los países anfitriones<br>como locales y no locales</b>'}
        ]
    )
]

# Botón individual para cada país
for i, pais in enumerate(paises): #Recorre paises y obtiene su posicion

    visibilidad = [False] * len(paises)
    visibilidad[i] = True


    botones.append( #Agregamos un boton a cada pais
        dict(
            label=f'🏅 {pais}',
            method='update', #Actualiza grafico cuando se presiona boton
            args=[
                {'visible': visibilidad},
                {'title': f'<b>{pais}: medallas promedio como local y no local</b>'}
            ]
        )
    )

# Diseño

fig_h3_paises.update_layout(

    title=dict(
        text='<b>Medallas promedio de los países anfitriones<br>como locales y no locales</b>',
        x=0.5,
        xanchor='center'
    ),

    template='plotly_dark',

    paper_bgcolor='#111111',
    plot_bgcolor='#111111',

    height=650,

    margin=dict(
        t=130,
        b=80,
        l=80,
        r=50
    ),

    # Menú desplegable
    updatemenus=[
        dict(
            buttons=botones,
            direction='down',
            showactive=True,
            x=0.02,
            xanchor='left',
            y=1.12,
            yanchor='top',
            bgcolor='#1C1C1C',
            bordercolor='#D4AF37',
            font=dict(
                color='white'
            )
        )
    ],

    xaxis=dict(
        title='Condición',
        title_font=dict(
            color='white',
            size=14
        ),
        tickfont=dict(
            color='#D9D9D9',
            size=13
        ),
        gridcolor='#292929'
    ),

    yaxis=dict(
        title='Promedio de medallas',
        title_font=dict(
            color='#D4AF37',
            size=14
        ),
        tickfont=dict(
            color='#D9D9D9'
        ),
        gridcolor='#292929',
        rangemode='tozero'
    ),

    # CAMBIO CLAVE: Permite ver la información del punto exacto bajo el cursor
    hovermode='closest',

    showlegend=False
)

# Mostrar gráfico
fig_h3_paises.show()

###Conclusión de hipótesis 3
Luego del análisis de los datos y de los gráficos realizados, podemos observar una diferencia importante en la cantidad promedio de medallas obtenidas por los países según su condición de localía. Los países analizados obtuvieron, en promedio, 36,89 medallas cuando fueron anfitriones, frente a 20,65 medallas en las ediciones en las que participaron sin serlo. Esto representa una diferencia de aproximadamente 16,24 medallas por edición.

Si bien existen casos particulares de países cuyos resultados no siguen la tendencia general, la comparación muestra que, en el conjunto analizado, la cantidad promedio de medallas es mayor cuando los países compiten como locales.

Por lo tanto, los resultados obtenidos respaldan la hipótesis planteada. Sin embargo, esta diferencia debe interpretarse como una asociación observada en los datos y no como una demostración de que la condición de anfitrión sea, por sí sola, la causa del aumento en la cantidad de medallas.